name: Deploy to GitHub Pages

# Run workflow on every push to the master branch
on:
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
        
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Environment
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'
        
    - name: Install dependencies
      working-directory: ./src
      run: dotnet restore
      
    - name: Build
      working-directory: ./src
      run: dotnet build --configuration Packing
      
    - name: Deploy Package 
      working-directory: ./src
      run: dotnet pack --configuration Packing --output ./nupkgs
    
    - name: Publish to Nuget.Org
      working-directory: ./src
      run: dotnet nuget push --skip-duplicate ./nupkgs/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_API_KEY}}
      
    - name: Publish to GitHub
      working-directory: ./src
      run: dotnet nuget push --skip-duplicate ./nupkgs/*.nupkg --source https://nuget.pkg.github.com/${{github.repository_owner}}/index.json --api-key ${{github.token}}

  deploy-to-github-pages:
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    steps:
    # uses GitHub's checkout action to checkout code form the master branch
    - uses: actions/checkout@v2
     
    - name: Copy files
      run: mkdir release && cp -fR published/wwwroot/* release/.    
    
    # changes the base-tag in index.html from '/' to 'SufficitBlazorClient' to match GitHub Pages repository subdirectory
    - name: Change base-tag in main.js from / to SufficitBlazorClient
      run: sed -i 's/rootPath\ =\ \"\";/rootPath\ =\ \"\/sufficit-blazor-client\";/g' release/assets/js/main.js
      
    # changes the base-tag in index.html from '/' to 'SufficitBlazorClient' to match GitHub Pages repository subdirectory
    - name: Change base-tag in index.html from / to SufficitBlazorClient
      run: sed -i 's/<base href="\/" \/>/<base href="\/sufficit-blazor-client\/" \/>/g' release/index.html
    
    # copy index.html to 404.html to serve the same file when a file is not found
    - name: copy index.html to 404.html
      run: cp release/index.html release/404.html

    # add .nojekyll file to tell GitHub pages to not treat this as a Jekyll project. (Allow files and folders starting with an underscore)
    - name: Add .nojekyll file
      run: touch release/.nojekyll
      
    - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: release
